// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Q6fK0Q3cJGWC4fsdoP3o52yOsb5HDFU',
    appId: '1:822000878801:web:4d084564e7ee66d2ca31f0',
    messagingSenderId: '822000878801',
    projectId: 'motor-bike-app',
    authDomain: 'motor-bike-app.firebaseapp.com',
    storageBucket: 'motor-bike-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvDkEM8mS4LNE_UrLxwHK3sjrVeIQLVw',
    appId: '1:822000878801:android:d86788d964d37cc9ca31f0',
    messagingSenderId: '822000878801',
    projectId: 'motor-bike-app',
    storageBucket: 'motor-bike-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp47XAN8ANNlou2aaIC0fz177fCWBE2-s',
    appId: '1:822000878801:ios:e1d1d7fd9977c54dca31f0',
    messagingSenderId: '822000878801',
    projectId: 'motor-bike-app',
    storageBucket: 'motor-bike-app.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp47XAN8ANNlou2aaIC0fz177fCWBE2-s',
    appId: '1:822000878801:ios:e1d1d7fd9977c54dca31f0',
    messagingSenderId: '822000878801',
    projectId: 'motor-bike-app',
    storageBucket: 'motor-bike-app.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Q6fK0Q3cJGWC4fsdoP3o52yOsb5HDFU',
    appId: '1:822000878801:web:5646f679fae593ccca31f0',
    messagingSenderId: '822000878801',
    projectId: 'motor-bike-app',
    authDomain: 'motor-bike-app.firebaseapp.com',
    storageBucket: 'motor-bike-app.appspot.com',
  );
}
